### ISSUE TITLE
steps.Changelog.outputs.changelog has the commit messages from the previous release.

### ISSUE THREAD

**Issue by prayeo** [ScottBrenner/generate-changelog-action#21]
Hello 

I thought it was a comfortable action, so I tested it to try it out.
I use it as follows, but it works by including the commit message of the last release each time a new release is made.

Could you please let me know if I am using it wrong?

workflow yml code

```
on:
  push:
    branches: [ master ]
    
env:
  VERSION: '0.3.12'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    ...
    
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Check changelog
      uses: scottbrenner/generate-changelog-action@master
      id: changelog

    - name: Create Release
      id: create-release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body: |
          ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false  
    
    ...
    
```   
   
![image](https://user-images.githubusercontent.com/29880418/110759322-d4154f80-8290-11eb-9e37-af49d47c315d.png)
